name: Execute Main Script

on:
  schedule:
    - cron: '0 9 * * *' # Executa todos os dias às 9 horas da manhã

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Environment Variables
      run: |
        echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV
        echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> $GITHUB_ENV
        echo "USER_KEY=${{ secrets.USER_KEY }}" >> $GITHUB_ENV
        echo "USER_SECRET=${{ secrets.USER_SECRET }}" >> $GITHUB_ENV

    - name: Run Main Script
      run: python main.py

